dist: xenial

language: node_js

node_js:
  - node
  - 14

env:
  global:
    - COVERALLS_PARALLEL=true
    - COVERALLS_SERVICE_NAME=travis-pro
    - COVERALLS_REPO_TOKEN=N1yHrKvfPGlfkXycpYxkWnHNhzkssRb8M
    - COVERALLS_GIT_BRANCH=main

addons:
  apt:
    packages:
      - make

script: make build

cache:
  - npm

os:
  - linux

notifications:
  webhooks: https://coveralls.io/webhook?repo_token=N1yHrKvfPGlfkXycpYxkWnHNhzkssRb8M
  email: restuwahyu13@gmail.com
